//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRM_GUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BRM : DbContext
    {
        public BRM()
            : base("name=BRM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bus> Buses { get; set; }
        public virtual DbSet<BusConnectingRoute> BusConnectingRoutes { get; set; }
        public virtual DbSet<BusDelay> BusDelays { get; set; }
        public virtual DbSet<BusDistributor> BusDistributors { get; set; }
        public virtual DbSet<BusGuide> BusGuides { get; set; }
        public virtual DbSet<BusRoute> BusRoutes { get; set; }
        public virtual DbSet<BusRouteDelay> BusRouteDelays { get; set; }
        public virtual DbSet<BusRouteMatch> BusRouteMatches { get; set; }
        public virtual DbSet<BusStop> BusStops { get; set; }
        public virtual DbSet<BusType> BusTypes { get; set; }
        public virtual DbSet<Delay> Delays { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Guide> Guides { get; set; }
        public virtual DbSet<HandlingViolation> HandlingViolations { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<SupportPrice> SupportPrices { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
