//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRM_GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusRoute()
        {
            this.BusConnectingRoutes = new HashSet<BusConnectingRoute>();
            this.BusRouteDelays = new HashSet<BusRouteDelay>();
            this.BusRouteMatches = new HashSet<BusRouteMatch>();
            this.BusRouteMatches1 = new HashSet<BusRouteMatch>();
        }
    
        public int busRouteId { get; set; }
        public string name { get; set; }
        public int busStopIdBegin { get; set; }
        public int busStopIdEnd { get; set; }
        public bool isMatch { get; set; }
        public Nullable<System.DateTime> atCreate { get; set; }
        public Nullable<System.DateTime> atUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusConnectingRoute> BusConnectingRoutes { get; set; }
        public virtual BusStop BusStop { get; set; }
        public virtual BusStop BusStop1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusRouteDelay> BusRouteDelays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusRouteMatch> BusRouteMatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusRouteMatch> BusRouteMatches1 { get; set; }
    }
}
