//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRM_GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusRouteMatch
    {
        public int busRouteIdParent { get; set; }
        public int busRouteIdChild { get; set; }
        public int numericalOrder { get; set; }
        public Nullable<System.DateTime> atCreate { get; set; }
        public Nullable<System.DateTime> atUpdate { get; set; }
    
        public virtual BusRoute BusRoute { get; set; }
        public virtual BusRoute BusRoute1 { get; set; }
    }
}
