//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRM_GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class HandlingViolation
    {
        public int hadlingViolationId { get; set; }
        public int busId { get; set; }
        public string dispatchNumber { get; set; }
        public Nullable<int> numberOfminutes { get; set; }
        public System.DateTime dateOfViolation { get; set; }
        public string body { get; set; }
        public string violationLevel { get; set; }
        public int penaltyRate { get; set; }
        public string currencyUnit { get; set; }
    
        public virtual Bus Bus { get; set; }
    }
}
